# Configuration for GitHub Pull Request Labeler
# This file is intentionally left minimal to prevent duplicate labels
# All labeling logic is handled by .github/workflows/auto-label.yml
#
# This file is kept to prevent the actions/labeler step from failing
# but all actual label definitions have been moved to auto-label.yml